schema_version = "1.0.0"
id = "bake_manager_tool"
version = "1.5.0"
name = "Bake Manager Tool"
tagline = "Physics cache management and bake automation"
maintainer = "hyeffect55 <hyeffect55@gmail.com>"
type = "add-on"
blender_version_min = "5.0.1"
license = ["SPDX:GPL-3.0-or-later"]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".git",
  "*.zip",
  "*.sh",
  ".idea",
  ".gitignore"
]